import { product } from "./types";
export const products: product[] = [
  {
    id: 1,
    name: "Muscle Tank",
    tagline: "T Shirts",
    price: 75,
    imgsrc: "/images/product-1.png",
    category: "female",
  },
  {
    id: 2,
    name: "Brushed Bomber",
    tagline: "Jackets",
    price: 225,
    imgsrc: "/images/product-2.png",
    category: "female",
  },
  {
    id: 3,
    name: "Raglan Sweatshirt",
    tagline: "Jackets",
    price: 195,
    imgsrc: "/images/product-3.png",
    category: "female",
  },
  {
    id: 4,
    name: "Brushed Raglan Sweatshirt",
    tagline: "Jackets",
    price: 195,
    imgsrc: "/images/product-4.png",
    category: "female",
  },
  {
    id: 5,
    name: "Cameryn Sash Tie Dress",
    tagline: "Jackets",
    price: 545,
    imgsrc: "/images/product-5.png",
    category: "female",
  },
  {
    id: 6,
    name: "Imperial Alpaca Hoodie",
    tagline: "Jackets",
    price: 525,
    imgsrc: "/images/product-10.png",
    category: "female",
  },
  {
    id: 7,
    name: "Flex Sweatshirt",
    tagline: "Jackets",
    price: 175,
    imgsrc: "/images/product-6.png",
    category: "female",
  },
  {
    id: 8,
    name: "Flex Push Button Bomber",
    tagline: "Jackets",
    price: 225,
    imgsrc: "/images/product-11.png",
    category: "male",
  },
  {
    id: 9,
    name: "Flex Sweatpants",
    tagline: "Jackets",
    price: 175,
    imgsrc: "/images/product-7.png",
    category: "female",
  },
  {
    id: 10,
    name: "Pink Fleece Sweatpants",
    tagline: "Jackets",
    price: 195,
    imgsrc: "/images/product-8.png",
    category: "female",
  },
  {
    id: 11,
    name: "Lite Sweatpants",
    tagline: "Jackets",
    price: 148,
    imgsrc: "/images/product-9.png",
    category: "female",
  },
];
